version: '3'
services:
  neo4j:
    image: neo4j:3.5
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./conf:/conf
      - ./data:/data
      - ./import:/import
      - ./logs:/logs
      - ./plugins:/plugins
    environment:
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms.memory.heap.initial_size=1G
      - NEO4J_dbms_memory_heap_max__size=1G
      - NEO4J_AUTH=neo4j/graphenauswertung
  app:
    build: .
    ports:
      - 80:80
    environment:
      - DATABASE_URL=bolt://database:7687
      - DATABASE_USER=neo4j
      - DATABASE_PASSWORD=graphenauswertung
    links:
      - "neo4j:database"
